project:
  type: website

website:
  title: "Forecasting in Python"
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/amyheather/forecasting
  sidebar:
    style: docked
    contents:
      - introduction.qmd
      - naive.qmd
      - evaluation.qmd
      - transformation.qmd
      - prophet.qmd
      - arima.qmd

format:
  html:
    theme: [simplex, style/theme.scss]
    css: style/style.css
    toc: true
    title-block-banner: images/banner.png