project:
  type: website

website:
  title: "Forecasting"
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/amyheather/forecasting
  sidebar:
    style: docked
    contents:
      - section: "Forecasting"
        contents:
        - introduction.qmd
        - naive.qmd
        - prophet.qmd
        - arima.qmd
        - other_methods.qmd
        - evaluation.qmd
      - section: "Ambulance Project"
        contents:
        - ambulance_paper.qmd
        - ambulance_notebook.qmd
        - ambulance_project.qmd

format:
  html:
    theme: [simplex, style/theme.scss]
    css: style/style.css
    toc: true
    title-block-banner: images/banner.png
    lightbox: true